[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "22"
postgres = "0.19"
serde = { version = "1.0", features = ["derive"] }
postgres-types = { version = "0.2", features = ["derive", "with-serde_json-1"] }
serde_json = "1.0"
google-cloud-pubsub = "0.22.0"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.79"
google-cloud-googleapis = "0.12.0"
futures = "0.3.30"
